messaging:
  image: dockerfile/rabbitmq:latest
  ports:
   - "5672:5672"
   - "15672:15672"
db:
  image: mongo:latest
  command: --smallfiles
  ports:
   - "27017:27017"
autho:
  image: httpprincess/authorizator:latest
  ports:
   - "5000:5000"
updater:
  image: httpprincess/store-updater:latest
  links:
    - db
    - messaging
worker:                                                                                                                                                                                                                                                                        
  image: benedicere/metahosting-dummyworker                                                                                                                                                                                                                                    
  links:                                                                                                                                                                                                                                                                       
    - db                                                                                                                                                                                                                                                                       
    - messaging                                                                                                                                                                                                                                                                
#  command: /app/run.py
worker2:
  image: benedicere/metahosting-dummyworker
  links:
    - db
    - messaging
  environment:
    - DB_LOCAL_COLLECTION=dummy2-local-instances
    - WORKER_NAME=dummy2
    - WORKER_DESCRIPTION=dummyworkerdd
facade:
   image: facade
   links:
    - db
    - autho
    - messaging
    - updater
