messaging:
  image: rabbitmq:3
db:
  image: mongo:latest
  command: --smallfiles
autho:
  image: httpprincess/authorizator:latest
updater:
  image: httpprincess/store-updater:latest
  links:
    - db
    - messaging
worker:                                                                                                                                                                                                                                                                        
  image: benedicere/metahosting-dummyworker                                                                                                                                                                                                                                    
  links:                                                                                                                                                                                                                                                                       
    - db                                                                                                                                                                                                                                                                       
    - messaging                                                                                                                                                                                                                                                                
worker2:
  image: benedicere/metahosting-dummyworker
  links:
    - db
    - messaging
  environment:
    - DB_LOCAL_COLLECTION=dummy2-local-instances
    - WORKER_NAME=dummy2
    - WORKER_DESCRIPTION=dummyworkerdd
facade:
   image: facade
   links:
    - db
    - autho
    - messaging
    - updater
   command: python /app/client.py
